"""empty message

Revision ID: 77e769225c6a
Revises: 2265e4bcc089
Create Date: 2020-11-30 16:38:59.729145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e769225c6a'
down_revision = '2265e4bcc089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'type')
    # ### end Alembic commands ###
